version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    environment:
      PHP_HOST: app
    depends_on: 
      - app
      - db

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    hostname: app
    env_file:
      - .env
    ports:
      - 23456:23456
    depends_on: 
      - db
    links:
      - db:db
    volumes:
      - app-data:/usr/src/app # named volume
      - /usr/src/app/node_modules # anonymous volume for node_modules only    

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=terraform
      - MYSQL_USER=terraform
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
    driver: local
  app-data:
    driver: local
