version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
      - db
    networks:
      internal:
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    env_file: .env
    environment:
      DB_HOST: db.mokmok.local
      JWT_SECRET: your_jwt_secret_phrase
      JWT_EXPIRES_IN: 30m
    ports:
      - 23456:23456
    depends_on:
      - db
    networks:
      internal:
        aliases:
          - backend.mokmok.local
    volumes:
      - backend-data:/usr/src/backend # named volume
      - /usr/src/backend/node_modules # anonymous volume for node_modules only
    restart: always

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=terraform
      - MYSQL_USER=terraform
      - MYSQL_PASSWORD=password
    networks:
      internal:
        aliases:
          - db.mokmok.local
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d

networks:
  internal:

volumes:
  mysql-data:
    driver: local
  backend-data:
    driver: local
