version: 2.1

orbs:
  node: circleci/node@1.1.6
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-ecs: circleci/aws-ecs@0.0.3

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  build:
    docker:
      - image: node:12-alpine
    steps:
      - checkout
      - run:
          name: Install aws-cli
          command: |
            apk add --no-cache --update py-pip
            pip install awscli
      - run:
          name: Login ECR
          command: |
            aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${AWS_ECR_ACCOUNT_URL}
      - run:
          name: Build Image
          command: |
            docker build -t ${AWS_ECR_ACCOUNT_URL}:$CIRCLE_SHA1 -t ${AWS_ECR_ACCOUNT_URL}:latest .

workflows:
  build_and_push_image:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          repo: '${AWS_RESOURCE_NAME_PREFIX}'
          requires:
            - test
          filters:
            branches:
              only: master
