version: 2.1

orbs:
  node: circleci/node@1.1.6
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-ecs: circleci/aws-ecs@0.0.3

jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install aws-cli
          command: |
            sudo pip install awscli
      - run:
          name: Download jq
          command: |
            wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
            mv jq-linux64 jq
      - run:
          name: Login ECR
          command: |
            aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${AWS_ECR_ACCOUNT_URL}
      - run:
          name: Deploy
          command: |
            aws ecs describe-task-definition --task-definition webapp-service | jq '.taskDefinition | { containerDefinitions: .containerDefinitions }' > definition.json
            aws ecs register-task-definition --family webapp-service --cli-input-json file://definition.json
            aws ecs update-service --cluster sample-ecs-cluster --service webapp-service --task-definition webapp-service

workflows:
  build_and_push_image:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          repo: '${AWS_RESOURCE_NAME_PREFIX}'
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires: 
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: master        
